name: Build and deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
            - '3.10'
            - '3.11'
            - '3.12'
    steps:
      - name: ğŸ›ï¸ | Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ | Use Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: ğŸ§³ | Install Nuitka and dependencies
        run: |
          pip install --no-python-version-warning --disable-pip-version-check nuitka
          pip install --no-python-version-warning --disable-pip-version-check -r requirements.txt
          pip install --no-python-version-warning --disable-pip-version-check .
        working-directory: .

      - name: ğŸ“‚ | Print working directory
        run: cd . && pwd

      - name: ğŸ“‚ | List directory contents
        run: ls -R
        working-directory: .

      - name: ğŸ“œ | List environment variables
        run: |
          env | sort
        working-directory: .
      
      - name: ğŸ“¦ | Run Nuitka
        run: |
          python -m nuitka --version
          python -m nuitka --onefile --windows-icon-from-ico=icon.ico --enable-plugin=tk-inter --static-libpython=yes --follow-imports --assume-yes-for-downloads main.py
        working-directory: .

      - name: ğŸ—ƒï¸ | Upload working dir
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: .
